import json
import numpy as np

'''
Input: state.npz and run.json generated by parse_sugarscape.py 
Output: pass/fail  
Checks if the parser generate a valid run.json + state.npz pair, with any optional helper files consistent with them. 
That pair is the main package that the visualizer will use, and it should be self-consistent and complete.
- state.npz holds the actual numeric data: timesteps,grids
- run.json holds the metadata/instructions: dimensions, value range, timestep count, output file paths, visualization flags.
This validation script is a critical safety check before we attempt to visualize. It ensures that the data we feed into the visualizer is well-formed and matches the declared metadata.

Optional extras: entities_long.csv, grid_long.csv
- entites_long.csv is all *_AGENT.csv files combined into one long table with columns (timestep,id,x,y,wealth,age,deathAge,isMale,isFertile). This is not needed for the basic heatmap visualization, but it can be useful for debugging and future extensions.
- grid_long.csv is all *_GRID.csv files combined into one long table with columns (timestep,x,y,value). This is not strictly needed for the basic heatmap visualization, but it can be useful for debugging and future extensions.


'''
def load_run_config(path="run.json"):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def validate_grid_npz(config_path="run.json"):
    cfg = load_run_config(config_path)

    npz_path = cfg["outputs"]["grid_npz"]
    dims = cfg["run"]["dimensions"]
    H = int(dims["height"])
    W = int(dims["width"])

    value_range = cfg["run"].get("value_range", None)

    data = np.load(npz_path)

    if "timesteps" not in data or "grids" not in data:
        raise ValueError("NPZ must contain 'timesteps' and 'grids' arrays")

    timesteps = data["timesteps"]
    grids = data["grids"]

    if timesteps.ndim != 1:
        raise ValueError(f"timesteps must be 1D, got shape {timesteps.shape}")

    if grids.ndim != 3:
        raise ValueError(f"grids must be 3D (T,H,W), got shape {grids.shape}")

    if grids.shape[0] != len(timesteps):
        raise ValueError("Mismatch: len(timesteps) != grids.shape[0]")

    if grids.shape[1] != H or grids.shape[2] != W:
        raise ValueError(f"Grid shape mismatch. Expected (T,{H},{W}), got {grids.shape}")

    if not np.issubdtype(grids.dtype, np.floating) and not np.issubdtype(grids.dtype, np.integer):
        raise ValueError(f"grids must be numeric, got dtype {grids.dtype}")

    if value_range:
        vmin = float(value_range["min"])
        vmax = float(value_range["max"])
        gmin = float(np.nanmin(grids))
        gmax = float(np.nanmax(grids))
        if gmin < vmin or gmax > vmax:
            raise ValueError(f"Grid values out of range [{vmin}, {vmax}]: observed [{gmin}, {gmax}]")

    return True


if __name__ == "__main__":
    validate_grid_npz("run.json")
    print("Validation passed.")